### ISSUE TITLE
Search random image without specifying tags throws invalid json error.

### ISSUE THREAD

**Issue by Veetaha** [octet-stream/dinky#1]
When you run
```js
await dinky().search().random()
```
it throws 
```
FetchError: invalid json response body at 
https://derpibooru.org/search.json?random_image=true reason: 
Unexpected end of JSON input
```

Its because this request results in an empty body.
```
https://derpibooru.org/search.json?random_image=true
```

You should set `q=*` parameter when there are no tags specified in order to resolve the issue.

**Comment by octet-stream** [comment]
Hello, thanks for the feedback.
Sure I can add default search params for `.random()` :)

**Comment by octet-stream** [comment]
Fixed #1 in [v0.7.1](https://github.com/octet-stream/dinky/releases/tag/v0.7.1)

**Comment by Veetaha** [comment]
@octet-stream Thanks ))

**Comment by Veetaha** [comment]
@octet-stream Wait, it still crashes when you pass an empty array `dinky.search([]).random()` .
I suppose it's because your internal function when called `flat([[]])` returns `[undefined]` which gets stored in `search._query` map under `"q"` key and your condition isn't triggered.
```js
    const params = this._query.get("q")
    if (isArray(params) && params.length > 0) {
      this._query.set("q", params.join(","))
    } else if (this._query.has("random_image")) {
      // Add wildcard when searching for random image,
      // but no tags has been set
      this._query.set("q", "*")
    }
```

**Comment by octet-stream** [comment]
@Veetaha The question is why do you need to call .search() with empty array?

**Comment by Veetaha** [comment]
Because there is no prerequisite and this may happen when the user specifies no tags. According to the [null object pattern](https://en.wikipedia.org/wiki/Null_object_pattern) this should work as if I haven't passed any tag at all.

**Comment by octet-stream** [comment]
When user specify no tags, the `.tags()` method (which is used in [`Search`](https://github.com/octet-stream/dinky/blob/a1bef2116462bda8a8b6b4a88d357a61f60b3696/lib/Search.js#L21-L23) constructor when you call `Dinky#search()` with anything but `undefined`) [expect `list` argument to be `undefined`](https://github.com/octet-stream/dinky#tagslist---search) when not tags has been set.
So you **must** call this method without any arguments.

**Comment by octet-stream** [comment]
But I will take a look why `flat()` returns `[undefined]`, anyway :)

**Comment by octet-stream** [comment]
Yeah, of course it crashed on `flat()` since I have no tests for that utility, lol.

**Comment by octet-stream** [comment]
And because I didn't expect this use case.

**Comment by octet-stream** [comment]
Okay, try [`v0.7.2`](https://github.com/octet-stream/dinky/releases/tag/v0.7.2)
Hope this helps.

**Comment by Veetaha** [comment]
@octet-stream Yeah, great, thanks a lot!

**Comment by octet-stream** [comment]
Glad to hear that.
Do not be shy to re-open this issue, if you still have related problems.
Or just open a new one.
Thanks again for the feedback.
